In [88]:
import numpy as np
import pandas as pd

In [90]:
dict={} 

In [92]:
dict={'name':['yashita','yash','ansh'],'cgpa':[9.5,2.3,4.5],'marks':[950,40,60]}

In [94]:
dict

{'name': ['yashita', 'yash', 'ansh'],
 'cgpa': [9.5, 2.3, 4.5],
 'marks': [950, 40, 60]}

In [96]:
dict['name'][2]

'ansh'

In [98]:
dit={}

In [100]:
dit['name']='day'
dit['cgpa']=9.8
dit['marks']=60

In [102]:
dict.keys()

dict_keys(['name', 'cgpa', 'marks'])

In [104]:
dict.values()

dict_values([['yashita', 'yash', 'ansh'], [9.5, 2.3, 4.5], [950, 40, 60]])

In [106]:
dict.items()

dict_items([('name', ['yashita', 'yash', 'ansh']), ('cgpa', [9.5, 2.3, 4.5]), ('marks', [950, 40, 60])])

In [108]:
dict.get('name')

['yashita', 'yash', 'ansh']

In [110]:
number={1,2,3,4,2,3,4}

In [112]:
number

{1, 2, 3, 4}

In [114]:
len(number)

4

In [116]:
number.add(5)

In [118]:
number

{1, 2, 3, 4, 5}

In [120]:
number.remove(2)

In [122]:
number

{1, 3, 4, 5}

In [124]:
number.pop()

1

In [126]:
type(number)

set

In [128]:
type(dict)

dict

In [130]:
dict.pop('marks')

[950, 40, 60]

In [132]:
dict

{'name': ['yashita', 'yash', 'ansh'], 'cgpa': [9.5, 2.3, 4.5]}

In [134]:
tup=(1,2,3,4,5,6,7,8,'hi',7,6)

In [136]:
tup

(1, 2, 3, 4, 5, 6, 7, 8, 'hi', 7, 6)

In [138]:
ff=set(tup)

In [140]:
type(ff)

set

In [142]:
lis=[1,2,'hi',4,5,'hello']

In [144]:
a=np.random.random([3,4])

In [155]:
b=np.random.random([3,4])

In [157]:
a

array([[0.53006857, 0.23546173, 0.16490859, 0.95256009],
       [0.25721572, 0.40774581, 0.20524406, 0.69887975],
       [0.74444864, 0.23233952, 0.2007267 , 0.65102942]])

In [159]:
b

array([[7.58047356e-02, 8.56470479e-01, 3.31526021e-01, 4.70846129e-01],
       [7.86281099e-01, 2.87597534e-01, 7.28709304e-04, 8.96780059e-01],
       [5.77664121e-01, 9.39950357e-02, 3.44542058e-02, 7.77947916e-01]])

In [187]:
a+b



array([[0.6058733 , 1.0919322 , 0.49643461, 1.42340622],
       [1.04349682, 0.69534335, 0.20597277, 1.59565981],
       [1.32211276, 0.32633456, 0.23518091, 1.42897733]])

In [167]:
c=np.random.random(5)

In [169]:
c

array([0.73946497, 0.60297131, 0.20574014, 0.95525662, 0.37191712])

In [179]:
d=np.random.random(5)

In [181]:
d

array([0.75187548, 0.94908623, 0.5937002 , 0.91855607, 0.58340529])

In [183]:
c+d

array([1.49134045, 1.55205754, 0.79944034, 1.87381269, 0.95532241])

In [189]:
a-b

array([[ 0.45426383, -0.62100875, -0.16661743,  0.48171396],
       [-0.52906538,  0.12014828,  0.20451535, -0.19790031],
       [ 0.16678452,  0.13834448,  0.1662725 , -0.1269185 ]])

In [191]:
a*b

array([[4.01817074e-02, 2.01666017e-01, 5.46714887e-02, 4.48509231e-01],
       [2.02243859e-01, 1.17266691e-01, 1.49563253e-04, 6.26741424e-01],
       [4.30041267e-01, 2.18387615e-02, 6.91587913e-03, 5.06466978e-01]])

In [199]:
np.dot(c,d)

2.3448404902070745

In [201]:
np.mean(a)

0.44005238247668377

In [203]:
np.median(a)

0.3324807673977092

In [205]:
np.std(a)

0.25536213258365204

In [207]:
np.sqrt(a)

array([[0.72805808, 0.48524399, 0.40608939, 0.97599185],
       [0.50716439, 0.63854977, 0.45303869, 0.83599028],
       [0.86281437, 0.4820161 , 0.44802534, 0.80686394]])

In [211]:
np.argmax(a)

3

In [217]:
a

array([[0.53006857, 0.23546173, 0.16490859, 0.95256009],
       [0.25721572, 0.40774581, 0.20524406, 0.69887975],
       [0.74444864, 0.23233952, 0.2007267 , 0.65102942]])

In [219]:
np.argmax(a,axis=0)

array([2, 1, 1, 0], dtype=int64)

In [221]:
np.argmax(a,axis=1)

array([3, 3, 0], dtype=int64)